<?php

/**
 * @file
 * Tide Site Simple Sitemap functions.
 */

use Drupal\simple_sitemap\Entity\SimpleSitemapInterface;
use Drupal\simple_sitemap\Entity\SimpleSitemap;

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function tide_site_simple_sitemap_taxonomy_term_delete($term) {
  // Remove the sitemap of the deleted site term¡.
  try {
    /** @var \Drupal\taxonomy\TermInterface $term */
    if ($term->bundle() == 'sites') {
      $sitemap_id = 'site-' . $term->id();
      $sitemap = SimpleSitemap::load($sitemap_id);
      $sitemap_storage = \Drupal::entityTypeManager()->getStorage('simple_sitemap');
      if ($sitemap instanceof SimpleSitemapInterface) {
        $sitemap_storage->deleteContent($sitemap);
        $sitemap_storage->load($sitemap_id)->delete();
      }
    }
  }
  catch (Exception $exception) {
    watchdog_exception('tide_site_simple_sitemap', $exception);
  }
}
